---
name: User-guides alphabetic ordering
on:
  push:
    paths:
      - 'get-started/faq/index.md'
  pull_request:
    paths:
      - 'get-started/faq/index.md'
jobs:
  alphabetic-order:
    name: User-guides alphabetic ordering
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends python3-pip
          sudo pip install beautifulsoup4 PyYAML
      - name: Alphabetic-order script
        run: |
          python3 .github/workflows/alphabetic-faq.py
