on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get install -y tor
        curl -IL --socks5-hostname 127.0.0.1:9050 http://dvirnr6squ4k5inagl6cmo4oikclm4fotmsicquefqutpyzzbumet3yd.onion:18081
