on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageWindows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Download files from Monero-GUI build.yml
      uses: dawidd6/action-download-artifact@v2.21.1
      with:
        workflow: build.yml
        workflow_conclusion: success
        run_id: ${{ github.event.inputs.runid }}
        repo: monero-project/monero-gui
        skip_unpack: true
    - run: dir
    - name: "extract win zip"
      run: |
        dir
        Expand-Archive -Path docker-windows-static.zip -DestinationPath .
    - name: "create installer"
      run: |
          #Known hashes ~ files installed from innosetup-6.2.1.exe
          $path_inno_files = "helper-scripts\inno_setup"
          #assume opengl file is in homedir
          (Get-FileHash $path_inno_files\Default.isl).hash -eq "179da3422d7bbb65bb2052f9c0b370ab66ddd6f24693d90accbd7d7d73d4f1a4"
          (Get-FileHash $path_inno_files\ISCC.exe).hash -eq "0d02e30a6ad432a50eb86f1ecf330147046e671de340bcb43a170fecbd19bf51"
          (Get-FileHash $path_inno_files\ISCmplr.dll).hash -eq "5ea9bb338795bffa33da5581e5fe1c976a561f6dc32105635dcd518fbb5a33b4"
          (Get-FileHash $path_inno_files\islzma.dll).hash -eq "0b2e19e473a47e10578b05a2f3b43ad96603f3ee1e397c06a280c3b7458a76e2"
          (Get-FileHash $path_inno_files\ISPPBuiltins.iss).hash -eq "a7c5a10f4aac60862082985cfdf8bc5e703fa7fb9cfff4e1deb1d9452862057f"
          (Get-FileHash $path_inno_files\Setup.e32).hash -eq "088622096c373250d04e46de5cda072a921a89900c57988bbe52f1e308e48043"
          (Get-FileHash $path_inno_files\SetupLdr.e32).hash -eq "86154d725c21660f220e957eb6dcaf73ca609eef486dcdce6d5d7c286abd03d5"
          (Get-FileHash $path_inno_files\ISPP.dll).hash -eq "1be06b60090221d7a7d236d374ab4ff7e6a56013107f806be4bea2b79dad3703"
          (Get-FileHash opengl32sw.dll).hash -eq "963641a718f9cae2705d5299eae9b7444e84e72ab3bef96a691510dd05fa1da4"

          $TAG = "${{ github.event.inputs.tag }}"
          $INNO_FILES = "helper-scripts\inno_setup\"
          
          Invoke-WebRequest -Uri "https://gui.xmr.pm/files/cli/$($TAG)/monero-win-x64-$($TAG).zip" -OutFile "monero-win-x64-$($TAG).zip"
          Invoke-WebRequest -Uri "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf" -OutFile "monero-gui-wallet-guide.pdf"
          New-Item "start-low-graphics-mode.bat"
          $lowgfx = @"
          @echo off
          
          set QMLSCENE_DEVICE=softwarecontext
          
          start /b monero-wallet-gui.exe
          "@
          
          Set-Content "start-low-graphics-mode.bat" $lowgfx
          
          7z x monero-win-x64-$($TAG).zip
          
          mkdir -p dummy\monero-gui-$($TAG)\extras
          $HEAD = "monero-x86_64-w64-mingw32-$($TAG)"
          cd $HEAD
          Move-Item -Path LICENSE -Destination ..\dummy\monero-gui-$($TAG)
          Move-Item -Path monerod.exe -Destination ..\dummy\monero-gui-$($TAG)
          
          rm README.md
          rm ANONYMITY_NETWORKS.md
          
          cd ..
          
          $dest = "dummy\monero-gui-$($TAG)"
          Move-Item -Path monero-gui-wallet-guide.pdf -Destination $dest
          Move-Item -Path monero-wallet-gui.exe -Destination $dest
          Move-Item -Path opengl32sw.dll -Destination $dest
          Move-Item -path start-low-graphics-mode.bat -Destination $dest
          
          Get-ChildItem -Path "$($HEAD)\*" -Recurse | Move-Item -Destination "dummy\monero-gui-$($TAG)\extras"
          
          mkdir inno; cd inno; git init
          git remote add -f origin https://github.com/monero-project/monero-gui
          git sparse-checkout init
          git sparse-checkout set "installers\windows"
          git pull origin master
          mkdir installers\windows\bin; cd ..
          Copy-Item -Path "$($dest)\*" -Destination "inno\installers\windows\bin" -Recurse
          
          $file = 'inno\installers\windows\Monero.iss'
          $strip_v = $TAG.substring(1,$TAG.length - 1)
          $content = Get-Content $file
          $new_str = '#define GuiVersion "' + $strip_v + '"'
          $content[3] = $new_str
          $content | Set-Content $file
          
          Copy-Item -Path "helper-scripts\inno_setup\*" -Destination "inno\installers\windows" -Recurse
          $inno_cc = "ISCC.exe"
          
          cd inno\installers\windows
          #type is == cat
          #type Monero.iss
          
          echo "RUN INNO"
          .\ISCC.exe Monero.iss
          echo "FNISHED INNO"
          
          #rename exe
          mv ./inno/installers/windows/Output/mysetup.exe ./inno/installers/windows/Output/monero-gui-install-win-x64-${{ github.event.inputs.tag }}.exe
        
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
          path: ./dummy
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-install-win-x64-${{ github.event.inputs.tag }}.exe.zip
          path: ./inno/installers/windows/Output/mysetup.exe
    - uses: actions/upload-artifact@v3
      with:
          name: docker-linux-static.zip
          path: docker-linux-static.zip
          
  packageLinux:
    runs-on: ubuntu-latest
    needs: packageWindows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
    - uses: actions/download-artifact@v3
      with:
        name: monero-gui-install-win-x64-${{ github.event.inputs.tag }}.exe
    - uses: actions/download-artifact@v3
      with:
        name: docker-linux-static.zip
    - run: |
          echo "CHECK ENV"
          ls -la
          TAG=${{ github.event.inputs.tag }}

          wget -q "https://gui.xmr.pm/files/cli/${TAG}/monero-linux-x64-${TAG}.tar.bz2"
          wget -q "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf"

          #extract monero-wallet-gui and 'unused' monerod
          unzip -a docker-linux-static.zip

          #create appimage
          cat <<EOF >> monero-wallet-gui.AppImage
          ./monero-wallet-gui
          EOF

          chmod -R 755 monero-wallet-gui.AppImage
          chmod -R 755 monero-wallet-gui
          
          #extract cli files
          tar -xvf "monero-linux-x64-${TAG}.tar.bz2"

          mkdir -p monero-gui-${TAG}/extras

          HEAD=monero-x86_64-linux-gnu-
          mv ${HEAD}${TAG}/LICENSE monero-gui-${TAG}/.
          mv ${HEAD}${TAG}/monerod monero-gui-${TAG}/.
          rm ${HEAD}${TAG}/README.md
          rm ${HEAD}${TAG}/ANONYMITY_NETWORKS.md

          cp monero-gui-wallet-guide.pdf monero-gui-${TAG}/.
          cp monero-wallet-gui monero-gui-${TAG}/.
          cp monero-wallet-gui.AppImage monero-gui-${TAG}/.

          chmod -R 644 monero-gui-${TAG}/monero-gui-wallet-guide.pdf 
          chmod -R 644 monero-gui-${TAG}/LICENSE
          
          ls -la 
          echo "BEFORE CHMOD"
          for filename in ${HEAD}${TAG}/*; do
            chmod -R 755 ${filename} 
            mv ${filename} monero-gui-${TAG}/extras/. 
          done

          mkdir dummy
          sudo mv monero-gui-${TAG} dummy/
          
          #mkdir uploadme
          #cp monero-gui-win-x64-${TAG}.zip uploadme/.
          #cp monero-gui-install-win-x64-${TAG}.exe uploadme/.
          monero-gui-v0.18.0.0
          cd dummy
          tar -cvjSf monero-gui-linux-x64-${TAG}.tar.bz2 monero-gui-${TAG}
          cd ..
          #cp monero-gui-linux-x64-${TAG}.tar.bz2 uploadme/.
          
          ls uploadme/*
          
          #$ scp -r uploadme user@host.com:/var/www/html/target_dir
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-linux-x64-${{ github.event.inputs.tag }}.tar.bz2
          path: ./dummy
          
