on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageGui:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.runid }}
          repo: monero-project/monero-gui
          skip_unpack: true
      - run: |
          TAG=${{ github.event.inputs.tag }}

          wget -q "https://gui.xmr.pm/files/cli/${TAG}/monero-linux-x64-${TAG}.tar.bz2"
          wget -q "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf"

          #extract monero-wallet-gui and 'unused' monerod
          unzip -a docker-linux-static.zip

          #create appimage
          cat <<EOF >> monero-wallet-gui.AppImage
          ./monero-wallet-gui
          EOF

          chmod -R 755 monero-wallet-gui.AppImage
          chmod -R 755 monero-wallet-gui

          tar -xvf "monero-linux-x64-${TAG}.tar.bz2"

          mkdir -p monero-gui-${TAG}/extras

          HEAD=monero-x86_64-linux-gnu-
          mv ${HEAD}${TAG}/LICENSE monero-gui-${TAG}/.
          mv ${HEAD}${TAG}/monerod monero-gui-${TAG}/.
          rm ${HEAD}${TAG}/README.md
          rm ${HEAD}${TAG}/ANONYMITY_NETWORKS.md

          cp monero-gui-wallet-guide.pdf monero-gui-${TAG}/.
          cp monero-wallet-gui monero-gui-${TAG}/.
          cp monero-wallet-gui.AppImage monero-gui-${TAG}/.

          chmod -R 644 monero-gui-${TAG}/monero-gui-wallet-guide.pdf 
          chmod -R 644 monero-gui-${TAG}/LICENSE

          for filename in ${HEAD}${TAG}/*; do
            chmod -R 755 ${filename} 
            mv ${filename} monero-gui-${TAG}/extras/. 
          done

          #print hashes
          find monero-gui-${TAG} -type f -exec sha256sum {} \;
          tar -cvjSf monero-gui-linux-x64-${TAG}.tar.bz2 monero-gui-${TAG}
          ls -la
          - uses: actions/upload-artifact@v3
            with:
              name: testing
              path: ./monero-gui-linux-x64-v0.18.0.0.tar.bz2
