on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'URL of gui upload artifact'     
        required: true
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageGui:
    runs-on: ubuntu-latest
    steps:
    - run: |
        - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: build.yml
          workflow_conclusion: success
          repo: monero-project/monero-gui
          skip_unpack: true
        ls -la
