on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.runid }}
          repo: monero-project/monero-gui
          skip_unpack: true
      - run: |
          sudo apt-get install -y sshpass
          TAG=${{ github.event.inputs.tag }}

          wget -q "https://gui.xmr.pm/files/cli/${TAG}/monero-linux-x64-${TAG}.tar.bz2"
          wget -q "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf"

          #extract monero-wallet-gui and 'unused' monerod
          unzip -a docker-linux-static.zip

          #create appimage
          cat <<EOF >> monero-wallet-gui.AppImage
          ./monero-wallet-gui
          EOF

          chmod -R 755 monero-wallet-gui.AppImage
          chmod -R 755 monero-wallet-gui

          tar -xvf "monero-linux-x64-${TAG}.tar.bz2"

          mkdir -p monero-gui-${TAG}/extras

          HEAD=monero-x86_64-linux-gnu-
          mv ${HEAD}${TAG}/LICENSE monero-gui-${TAG}/.
          mv ${HEAD}${TAG}/monerod monero-gui-${TAG}/.
          rm ${HEAD}${TAG}/README.md
          rm ${HEAD}${TAG}/ANONYMITY_NETWORKS.md

          cp monero-gui-wallet-guide.pdf monero-gui-${TAG}/.
          cp monero-wallet-gui monero-gui-${TAG}/.
          cp monero-wallet-gui.AppImage monero-gui-${TAG}/.

          chmod -R 644 monero-gui-${TAG}/monero-gui-wallet-guide.pdf 
          chmod -R 644 monero-gui-${TAG}/LICENSE

          for filename in ${HEAD}${TAG}/*; do
            chmod -R 755 ${filename} 
            mv ${filename} monero-gui-${TAG}/extras/. 
          done

          #print hashes
          find monero-gui-${TAG} -type f -exec sha256sum {} \;
          tar -cvjSf monero-gui-linux-x64-${TAG}.tar.bz2 monero-gui-${TAG}
      - uses: actions/upload-artifact@v3
        with:
          name: monero-gui-linux-x64-${{ github.event.inputs.tag }}.tar.bz2
          path: monero-gui-linux-x64-${{ github.event.inputs.tag }}.tar.bz2
      - uses: actions/upload-artifact@v3
        with:
          name: docker-windows-static.zip
          path: docker-windows-static.zip
  
  packageWindows:
    runs-on: windows-2019
    needs: packageLinux
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
          name: docker-windows-static.zip
    - name: "extract win zip"
      run: 7z x docker-windows-static.zip
    - name: "create installer"
      run: |
          TAG=${{ github.event.inputs.tag }}
          wget -q "https://gui.xmr.pm/files/cli/${TAG}/monero-win-x64-${TAG}.zip"
          wget -q "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf"
          #extract monero-wallet-gui and 'unused' monerod
          7z x docker-windows-static.zip
          
          (
          echo @echo off
          echo Here is my second line\n
          echo set QMLSCENE_DEVICE=softwarecontext\n
          echo start /b monero-wallet-gui.exe
          )>"start-low-graphics-mode.bat"

          7zip x monero-win-x64-${TAG}.zip
          mkdir -p monero-gui-${TAG}/extras

          HEAD=monero-x86_64-w64-mingw32-
          mv ${HEAD}${TAG}\LICENSE monero-gui-${TAG}/.
          mv ${HEAD}${TAG}\monerod monero-gui-${TAG}/.
          rm ${HEAD}${TAG}\README.md
          rm ${HEAD}${TAG}\ANONYMITY_NETWORKS.md

          cp monero-gui-wallet-guide.pdf monero-gui-${TAG}\.
          cp monero-wallet-gui.exe monero-gui-${TAG}\.
          cp start-low-graphics-mode.bat monero-gui-${TAG}\.
          cp opengl32sw.dll monero-gui-${TAG}\.
          
          for filename in ${HEAD}${TAG}\*; do
            mv ${filename} monero-gui-${TAG}\extras\. 
          done
          #print hashes
          find monero-gui-${TAG} -type f -exec sha256sum {} \;

          7z a -tzip monero-gui-win-x64-${TAG}.zip .\monero-gui-${TAG}\*
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
          path: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
