on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'URL of gui upload artifact'     
        required: true
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
    getArtifact:
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        repo: monero-project/monero-gui
        skip_unpack: true


    packageGui:
      runs-on: ubuntu-latest
      steps:
      - run: |
          ls -la
