on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageWindows:
    runs-on: windows-2019
    steps:
    - name: "Upload files using SCP"
      run: |
        echo "Hello world" > hello.txt
        Install-Module -Name Posh-SSH
        New-Item auth.txt
        
        Set-Content auth.txt "${{ secrets.SSH_KEY }}"
        ssh-add auth.txt

        $computer = "${{ secrets.SCP_SERVER }}"
        $username = "${{ secrets.USER }}"
        $password = "hunter2" | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password
        $keyfile  = auth.txt
        Set-SCPItem -ComputerName $computer -KeyFile $keyfile -AcceptKey -Credential $credential -Path hello.txt -Destination /tmp -Verbose
