on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageWindows:
    runs-on: windows-2019
    steps:
    - name: "Upload files using SCP"
      run: |
        echo "Hello world" > hello.txt
        
        Install-Module -Name Posh-SSH -force
        $keystring = "${{ secrets.OLD_SSH }}"
        $computer = "${{ secrets.SCP_SERVER }}"
        $username = "${{ secrets.USER }}"
        $password = "hunter2" | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password

        #create remote dir 
        New-SFTPSession -ComputerName $computer -Credential $credential -KeyString $keystring -AcceptKey -Verbose
        New-SFTPItem -SessionId 0 -Path /tmp/testing -ItemType Directory
        
        #push file
        #Set-SCPItem -ComputerName $computer -KeyString $keystring -AcceptKey -Credential $credential -Path  .\uploadme -Destination /tmp/testing -Verbose

