on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"

jobs:
  packageWindows:
    runs-on: windows-2019
    steps:
    - name: "Upload files using SCP"
      run: |
        echo "Hello world" > hello.txt
        Install-Module -Name Posh-SSH
        Set-SCPItem -ComputerName$ ${{ secrets.SCP_SERVER }} -KeyString ${{ secrets.SSH_KEY }} -AcceptKey -Credential ${{ secrets.USER }} -Path hello.txt -Destination /tmp -Verbose
