on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"
jobs: 
  packageWindows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: dawidd6/action-download-artifact@v2.21.1
      with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.runid }}
          repo: monero-project/monero-gui
          skip_unpack: true
    - name: "extract win zip"
      run: |
        dir
        7z x docker-windows-static.zip
    - name: "create installer"
      run: |
          $TAG = "${{ github.event.inputs.tag }}"
          $INNO_FILES = "helper-scripts\inno_setup\"
          
          Invoke-WebRequest -Uri "https://gui.xmr.pm/files/cli/$($TAG)/monero-win-x64-$($TAG).zip" -OutFile "monero-win-x64-$($TAG).zip"
          Invoke-WebRequest -Uri "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf" -OutFile "monero-gui-wallet-guide.pdf"
          New-Item "start-low-graphics-mode.bat"
          $lowgfx = @"
          @echo off
          
          set QMLSCENE_DEVICE=softwarecontext
          
          start /b monero-wallet-gui.exe
          "@
          
          Set-Content "start-low-graphics-mode.bat" $lowgfx
          
          7z x monero-win-x64-$($TAG).zip
          
          mkdir -p dummy\monero-gui-$($TAG)\extras
          $HEAD = "monero-x86_64-w64-mingw32-$($TAG)"
          cd $HEAD
          Move-Item -Path LICENSE -Destination ..\dummy\monero-gui-$($TAG)
          Move-Item -Path monerod.exe -Destination ..\dummy\monero-gui-$($TAG)
          
          rm README.md
          rm ANONYMITY_NETWORKS.md
          
          cd ..
          
          $dest = "dummy\monero-gui-$($TAG)"
          Move-Item -Path monero-gui-wallet-guide.pdf -Destination $dest
          Move-Item -Path monero-wallet-gui.exe -Destination $dest
          Move-Item -Path opengl32sw.dll -Destination $dest
          Move-Item -path start-low-graphics-mode.bat -Destination $dest
          
          Get-ChildItem -Path "$($HEAD)\*" -Recurse | Move-Item -Destination "dummy\monero-gui-$($TAG)\extras"
          
          mkdir inno; cd inno; git init
          git remote add -f origin https://github.com/monero-project/monero-gui
          git sparse-checkout init
          git sparse-checkout set "installers\windows"
          git pull origin master
          mkdir installers/windows/bin; cd ..
          Copy-Item -Path "$($dest)\*" -Destination "inno\installers\windows\bin" -Recurse
          
          $file = 'inno\windows\installers\Monero.iss'
          $old = '#define GuiVersion GetFileVersion("bin\monero-wallet-gui.exe")'
          $strip_v = $TAG.substring(1,$TAG.length)
          (Get-Content $file) -replace $old, '#define GuiVersion "$($strip_v)"' | Set-Content $file
          
          .\$($INNO_FILES)\ISCC.exe $file
          
          #-mv "inno\installers\windows\Output\mysetup.exe" ".\monero-gui-install-win-x64-$($TAG).exe"
          
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
          path: ./dummy
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-install-win-x64-${{ github.event.inputs.tag }}.exe
          path: ./inno/installers/windows/Output/mysetup.exe

