on: 
  workflow_dispatch:
    inputs:
      guifile:
        description: 'run id'     
        required: true
        default: "2680356377"
      tag:
        description: 'Tag version'
        required: true
        default: "v0.18.0.0"
jobs: 
  packageWindows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: dawidd6/action-download-artifact@v2.21.1
      with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.runid }}
          repo: monero-project/monero-gui
          skip_unpack: true
    - name: "extract win zip"
      run: |
        dir
        7z x docker-windows-static.zip
    - name: "create installer"
      run: |
          $TAG = "${{ github.event.inputs.tag }}"
          Invoke-WebRequest -Uri "https://gui.xmr.pm/files/cli/$($TAG)/monero-win-x64-$($TAG).zip" -OutFile "monero-win-x64-$($TAG).zip"
          Invoke-WebRequest -Uri "https://github.com/monero-ecosystem/monero-GUI-guide/releases/download/v1.9/monero-gui-wallet-guide.pdf" -OutFile "monero-gui-wallet-guide.pdf"
          New-Item "start-low-graphics-mode.bat"
          Set-Content "start-low-graphics-mode.bat" '@echo off`r`n`r`nset QMLSCENE_DEVICE=softwarecontext`r`n`r`nstart /b monero-wallet-gui.exe'
          7z x monero-win-x64-$($TAG).zip
          mkdir -p dummy\monero-gui-$($TAG)\extras
          $HEAD = "monero-x86_64-w64-mingw32-$($TAG)"
          cd $HEAD
          dir
          Move-Item -Path LICENSE -Destination ..\dummy\monero-gui-$($TAG)
          Move-Item -Path monerod.exe -Destination ..\dummy\monero-gui-$($TAG)
          rm README.md
          rm ANONYMITY_NETWORKS.md
          cd ..
          $dest = "dummy\monero-gui-$($TAG)"
          Move-Item -Path monero-gui-wallet-guide.pdf -Destination $dest
          Move-Item -Path monero-wallet-gui.exe -Destination $dest
          Move-Item -Path opengl32sw.dll -Destination $dest
          Move-Item -path start-low-graphics-mode.bat -Destination $dest
          Get-ChildItem -Path "$($HEAD)\*" -Recurse | Move-Item -Destination "dummy\monero-gui-$($TAG)\extras"
          $files = Get-ChildItem -Path "$($HEAD)\*"
          foreach ($f in $files){
            sha256sum $f
          }
          $compress = @{
            Path = "dummy\"
            CompressionLevel = "Fastest"
            DestinationPath = "test2.Zip"
          }
          Compress-Archive @compress
          Compress-Archive -Path dummy\monero-gui-$($TAG) -DestinationPath monero-gui-win-x64-$($TAG).zip
    - uses: actions/upload-artifact@v3
      with:
          name: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
          path: monero-gui-win-x64-${{ github.event.inputs.tag }}.zip
    - uses: actions/upload-artifact@v3
      with:
          name: test2.zip
          path: test2.zip
